import { CRWideTicketDrawParameters } from './type';

export function encodeCRWideTicketParams(p: CRWideTicketDrawParameters): string {
	const arr: any[] = [
		p.background,
		+p.showBorder,
		+p.isHKWestKowloonStyle,
		p.offsetX,
		p.offsetY,
		+p.showWatermark,
		p.watermark,
		p.ticketNo,
		p.station1,
		p.station2,
		p.station1en,
		p.station2en,
		+p.doShowZhan,
		+p.doShowEnglish,
		+p.doUseHuaWenXinWei1,
		+p.doUseHuaWenXinWei2,
		p.routeIdentifier,
		p.date.toISOString(),
		p.time,
		p.carriage,
		p.seat1,
		p.seat2,
		p.seat3,
		p.seatClass,
		p.price,
		p.idNumber,
		p.passenger,
		+p.doShowPassenger,
		p.soldplace,
		p.turnstile,
		+p.showSoldPlaceDown,
		p.rightUpContentType,
		p.serialCode,
		p.qrCodeText,
		p.purchaseMethod.join(','),
		+p.doPurchaseMethodHaveCircle,
		+p.noSeat,
		+p.noCarriage,
		p.info1,
		p.info2,
		p.info3,
		p.message,
		p.messageAlign,
		+p.doShowMessage,
		p.info1TrainType,
		p.info1from,
		p.info1to,
	];

	// JSON → UTF-8 → Base64 (URL safe)
	const json = JSON.stringify(arr);
	const b64 = btoa(encodeURIComponent(json));
	return b64.replace(/\+/g, '-').replace(/\//g, '_').replace(/=+$/, '');
}

export function decodeCRWideTicketParams(str: string): CRWideTicketDrawParameters {
	const json = decodeURIComponent(atob(str.replace(/-/g, '+').replace(/_/g, '/')));
	const arr = JSON.parse(json);

	const [
		background,
		showBorder,
		isHKWestKowloonStyle,
		offsetX,
		offsetY,
		showWatermark,
		watermark,
		ticketNo,
		station1,
		station2,
		station1en,
		station2en,
		doShowZhan,
		doShowEnglish,
		doUseHuaWenXinWei1,
		doUseHuaWenXinWei2,
		routeIdentifier,
		date,
		time,
		carriage,
		seat1,
		seat2,
		seat3,
		seatClass,
		price,
		idNumber,
		passenger,
		doShowPassenger,
		soldplace,
		turnstile,
		showSoldPlaceDown,
		rightUpContentType,
		serialCode,
		qrCodeText,
		purchaseMethod,
		doPurchaseMethodHaveCircle,
		noSeat,
		noCarriage,
		info1,
		info2,
		info3,
		message,
		messageAlign,
		doShowMessage,
		info1TrainType,
		info1from,
		info1to,
	] = arr;

	return {
		background,
		showBorder: !!showBorder,
		isHKWestKowloonStyle: !!isHKWestKowloonStyle,
		offsetX,
		offsetY,
		showWatermark: !!showWatermark,
		watermark,
		ticketNo,
		station1,
		station2,
		station1en,
		station2en,
		doShowZhan: !!doShowZhan,
		doShowEnglish: !!doShowEnglish,
		doUseHuaWenXinWei1: !!doUseHuaWenXinWei1,
		doUseHuaWenXinWei2: !!doUseHuaWenXinWei2,
		routeIdentifier,
		date: new Date(date),
		time,
		carriage,
		seat1,
		seat2,
		seat3,
		seatClass,
		price,
		idNumber,
		passenger,
		doShowPassenger: !!doShowPassenger,
		soldplace,
		turnstile,
		showSoldPlaceDown: !!showSoldPlaceDown,
		rightUpContentType,
		serialCode,
		qrCodeText,
		purchaseMethod: purchaseMethod.split(','),
		doPurchaseMethodHaveCircle: !!doPurchaseMethodHaveCircle,
		noSeat: !!noSeat,
		noCarriage: !!noCarriage,
		info1,
		info2,
		info3,
		message,
		messageAlign,
		doShowMessage: !!doShowMessage,
		info1TrainType,
		info1from,
		info1to,
	} as CRWideTicketDrawParameters;
}
