'use client';

import { Divider } from '@/components/InfrastructureCompo/Divider';
import OuterLink from '@/components/InfrastructureCompo/OuterLink';
import { useLocale } from '@/utils/hooks/useLocale';

export default function About() {
	const { t, locale } = useLocale();

	return (
		<>
			<div className="bg-[#edfdf8] border border-gray-400 rounded-[6px] py-8 px-4 lg:px-8 m-2 lg:mx-[20%] mb-10">
				{locale === 'ja' ? (
					<div className="flex flex-col p-2">
						<p>
							　SimTicket <span className="font-bold">内部テスト版</span>へようこそ～
						</p>
						<p>
							　開発者の <OuterLink link="https://x.com/elpwc">うに</OuterLink> です。
						</p>
						<p>　simTicket は、2025年10月に CR（中国国鉄）が紙製乗車券（正しく言うと精算用領収書）を完全廃止したことをきっかけに制作したオンライン鉄道切符ジェネレーターです</p>
						<p>　現在はまだ開発途中ですが、10月22日にテスト用URLが突然流出・拡散されたため、未完成ながらも内部テストという形で一般公開することにしました</p>
						<p>　そのため、未実装の機能や不具合が多く存在しますが、もしよければフィードバックをお寄せいただければ大変うれしく存じ上げます。</p>
						<p>　今はCRの计算机客票（通称：紅票・藍票）の部分を済ませて、JRマルス券を開発している段階です</p>
						<p>　この２社以外にも、TR、VNR、THSR など、開発者自身が実際に乗車したことのある鉄道会社の鉄道切符ジェネレーターを開発していく予定です</p>
						<p>　切符にある要素をできる限り再現し、最も完成度の高い鉄道切符ジェネレーターを目指しています</p>
						<p>　卒論・乗り鉄・就活をしながら開発を行っているため、進捗は必ずしも早くないかもしれませんが、何卒ご理解のほどお願いいたします</p>
						<br />
						<p>
							　開発進捗は、Twitterで随時更新中：<OuterLink link="https://x.com/elpwc">うに＠elpwc</OuterLink>
						</p>

						<br />
						<Divider />

						<p className="font-bold">TODO list:</p>
						<ul>
							<li className="text-green-700">・CR 計算機客票対応 ・・・◎完成</li>
							<li className="text-blue-700">・JR MARS券対応 ・・・△開発中</li>
							<li className="text-green-700">　・駅名編集器・レンダラー ・・・◎完成（2025-11-08）</li>
							<li className="text-blue-700">　・きっぷ種タイトル ・・・△開発中</li>
							<li className="">　・特急券、急行券、寝台券など対応 ・・・</li>
							<li className="">　・入場券 ・・・</li>
							<li className="">　・１２０ｍｍ券 ・・・</li>
							<li className="text-green-700">・多言語対応 ・・・◎完成（2025-11-05）</li>
							<li className="text-green-700">・生成結果の共有ページ（他ユーザーが作成したチケットを閲覧できるギャラリー機能） ・・・◎完成（2025-11-28）</li>
							<li className="">・JNR ・・・</li>
							<li className="">・JR近距離きっぷ ・・・</li>
							<li className="">・看板っこを描く ・・・（絶賛草稿中）</li>
						</ul>
						<br />

						<p>開発に際してご協力・助言をくださったすべての方に心より感謝いたします。</p>
						<br />
						<div className="border my-4 p-8 pb-16 bg-white text-[14px] flex flex-col gap-2">
							<p className="w-full text-center text-[18px]">免責事項</p>
							<p>　SimTicket は開発者自身の鉄道趣味で制作した娯楽および学習目的のための簡易ツールです。</p>
							<p>　本サイトは個人で楽しむ範囲の非営利仕様に限ってください。生成された画像やデータを商用利用や不正な目的での使用は固くお断りいたします。</p>
							<p>
								　もし、サイト内の構成・デザイン・掲載内容などにおいて、著作権その他の権利を侵害している可能性がありましたら、お手数ですがご連絡ください（elpwc@hotmail.com）。内容を確認のうえ、速やかに該当部分の削除など適切な対応を行います。
							</p>
							<p>
								　また、SimTicket によって生成された画像等が法令や条例に抵触しているとのご指摘をいただいた場合にも、確認後、迅速に関連部分の削除・修正などの対応を取らせていただきます。
							</p>
							<p>　開発者個人で運営している小規模なサイトのため、利用している鉄道ファンの皆さんにご理解・ご協力のほどよろしくお願いいたします。</p>
							<p className="text-right w-full">2025年 11月 28日</p>
							<p className="text-right w-full">うに（elpwc@hotmail.com）</p>
							<Divider />
							<p className="w-full text-center text-[18px]">Disclaimer</p>
							<p>　SimTicket is a simple tool created by the developer based on personal interest in railways, intended for entertainment and learning purposes.</p>
							<p>　This service is for personal, non-commercial use only. Use of generated images or data for commercial purposes or any unlawful activities is strictly prohibited.</p>
							<p>
								　If any content, design, or material on the site may potentially infringe copyrights or other rights, please contact me（elpwc@hotmail.com）. I will review the issue
								and promptly remove or take appropriate action.
							</p>
							<p>
								　Similarly, if any images or other outputs generated by SimTicket are found to violate laws or regulations, I will promptly delete or modify the relevant content upon
								confirmation.
							</p>
							<p>　As this service is operated on a small scale by an individual developer, I appreciate your understanding and cooperation.</p>{' '}
							<p className="text-right w-full">Nov. 28, 2025</p>
							<p className="text-right w-full">うに（elpwc@hotmail.com）</p>
							<br />
						</div>

						<br />
					</div>
				) : (
					<div className="flex flex-col p-2">
						<p>
							　欢迎使用 simTicket <span className="font-bold">内部测试版本</span>
						</p>
						<p>
							　simTicket 是在2025年10月 CR（中国国铁）彻底废止纸质报销凭证之际，由我（<OuterLink link="https://x.com/elpwc">うに＠elpwc</OuterLink>）开發的在线票面生成工具
						</p>
						<p>　目前 simTicket 还在未完成的开發阶段。但是由于测试网址在10月22日突然被泄露和广泛传播，于是我决定以半成品的形式先行向大家以内部测试的形式公开网页。</p>
						<p>　所以会出现不少未完成的功能和问题，欢迎大家反馈</p>
						<p>　目前已经完成了CR计算机客票（统称红票、蓝票）部分，正在开发JR MARS券部分</p>
						<p>　在这两社以外，我也计划制作 TR, VNR, THSR 等我坐过的铁道公司的车票制作器。</p>
						<p>　我会尽可能考虑、覆盖到票面上所有可能出现的情况，努力坐到最完美的车票制作器。</p>
						<p>　由于在一边准备毕业论文、去各地运转火车、找工作 一边在开發网站，开發进度可能不会很快，请谅解</p>
						<br />
						<p>
							　可以前往我的推特关注开發进度：<OuterLink link="https://x.com/elpwc">うに＠elpwc</OuterLink>
						</p>
						<br />
						<Divider />

						<p className="font-bold">TODO list:</p>
						<ul>
							<li className="text-green-700">・CR 計算機客票対応 ・・・◎完成</li>
							<li className="text-blue-700">・JR MARS券対応 ・・・△開発中</li>
							<li className="text-green-700">　・駅名編集器・渲染 ・・・◎完成（2025-11-08）</li>
							<li className="text-blue-700">　・券種标题 ・・・△開発中</li>
							<li className="">　・特急券、急行券、寝台券等 ・・・</li>
							<li className="">　・入場券 ・・・</li>
							<li className="">　・１２０ｍｍ券 ・・・</li>
							<li className="text-green-700">・多言語対応 ・・・◎完成（2025-11-05）</li>
							<li className="text-green-700">・生成结果共享页，可以鉴赏其他人发布的自制车票 ・・・◎完成（2025-11-28）</li>
							<li className="">・JNR ・・・</li>
							<li className="">・JR近距離きっぷ ・・・</li>
							<li className="">・看板娘 ・・・（絶賛草稿中）</li>
						</ul>
						<br />

						<p>在此感谢在开發过程中所有对我提供过帮助的人。</p>
						<br />

						<div className="border my-4 p-8 pb-16 bg-white text-[14px] flex flex-col gap-2">
							<p className="w-full text-center text-[18px]">免责声明</p>
							<p>　SimTicket 是由开發者个人基于铁道兴趣制作的娱乐及学习用途的简易工具。</p>
							<p>　本服务仅限个人非营利用途。严禁将生成的图片或数据用于任何商业目的或非法用途。</p>
							<p>　如果网站内容、设计或其他素材侵犯到了版权或其他权利，请与我联系（elpwc@hotmail.com）。我将在确认后，及时删除或采取适当的处理措施。</p>
							<p>　此外，如果 SimTicket 生成的图片等被认为违反法律法规或相关条例，我也将在确认后，迅速对相关部分进行删除或修改等处理。</p>
							<p>　由于本服务为开发者个人小规模运营，感谢所有使用的铁道迷的理解与配合。</p>
							<p className="text-right w-full">2025年 11月 28日</p>
							<p className="text-right w-full">うに（elpwc@hotmail.com）</p>
							<Divider />
							<p className="w-full text-center text-[18px]">Disclaimer</p>
							<p>　SimTicket is a simple tool created by the developer based on personal interest in railways, intended for entertainment and learning purposes.</p>
							<p>　This service is for personal, non-commercial use only. Use of generated images or data for commercial purposes or any unlawful activities is strictly prohibited.</p>
							<p>
								　If any content, design, or material on the site may potentially infringe copyrights or other rights, please contact me（elpwc@hotmail.com）. I will review the issue
								and promptly remove or take appropriate action.
							</p>
							<p>
								　Similarly, if any images or other outputs generated by SimTicket are found to violate laws or regulations, I will promptly delete or modify the relevant content upon
								confirmation.
							</p>
							<p>　As this service is operated on a small scale by an individual developer, I appreciate your understanding and cooperation.</p>
							<p className="text-right w-full">Nov. 28, 2025</p>
							<p className="text-right w-full">うに（elpwc@hotmail.com）</p>
							<br />
						</div>
					</div>
				)}
				<p className="text-right w-full">2025年 10月 23日 うに</p>
				<p className="text-right w-full">（更新）2025年 11月 28日 うに</p>
				<p className="text-right w-full">（更新）2025年 12月 02日 うに</p>
				<div className="text-[12px] text-[gray]">
					<div>
						Fonts made by<OuterLink link="http://www.webfontfree.com">Web Free Fonts</OuterLink>
						is licensed by Fonts made by<OuterLink link="http://creativecommons.org/licenses/by/4.0/">CC 4.0 BY</OuterLink>
					</div>
				</div>
			</div>
		</>
	);
}
