import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import Link from 'next/link';

const geistSans = Geist({
	variable: '--font-geist-sans',
	subsets: ['latin'],
});

const geistMono = Geist_Mono({
	variable: '--font-geist-mono',
	subsets: ['latin'],
});

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
				<header>
					<nav className="bg-[#007fd4] text-white p-4 flex gap-10">
						<Link href="/">
							<div className="navitem">SimTicket</div>
						</Link>
						<Link href="/about">
							<div className="navitem">About</div>
						</Link>
					</nav>
				</header>
				<main>{children}</main>
			</body>
		</html>
	);
}
